Implement `Drop` for `FrameData`
RustAudio/rodio pull request #285
Opened 2020-04-22 11:44 UTC by stevebob

The types `Frame` and `FrameData` are mutually recursive, and the
incidental linked lists that can be formed as a result can be long (at
least in the order of thousands of elements). As a result, when a frame
is deallocated, rust appears to recursively call `drop_in_place` down
the list, causing stack overflows for long lists.

Addresses https://github.com/RustAudio/rodio/issues/283

This problem is hard to reproduce. I've tried constructing toy programs to no avail. The only way I've managed to trigger it is running https://github.com/stevebob/slime99/ `graphical` or `ansi-terminal` crates with the `--audio` flag (audio is disabled by default because of exactly this problem). Start a new game and leave it on the first floor for ~5 minutes, then walk down the stairs. The track will switch and _sometimes_ there will be a stack overflow on the "rodio audio processing" thread.

I was able to reliably reproduce the problem last night, but I'm trying to again now (after changing nothing) and it's not happening. Something something phase of the moon. In other words, I'm not satisfied with my testing of this patch thus far. I'm opening this PR now to start a discussion. Is there a way to construct a long chain of `Frame`->`FrameData`->`Frame`->...? I think doing so would reliably trigger this problem.

2020-04-22 13:13 UTC, stevebob commented
Ok I managed to reproduce it as per the above. My goal is to determine a correlation between the length of `Frame`->`FrameData` chain, and stack overflows. Then demonstrate that after my change, chains of problematic lengths no longer cause stack overflows.

I added the following right at the start of `FrameData`'s drop:
```rust
    fn drop(&mut self) {
        let mut count = 0;
        let mut cursor = self.next.lock().unwrap().clone();
        loop {
            if let Frame::Data(data) = &*cursor.clone() {
                let next = data.next.lock().unwrap();
                cursor = next.clone();
            } else {
                break;
            }
            count += 1;
        }
        println!("count: {}", count);
        return;
       ...
```
...to measure the length of the chain. As an added bonus, the above code runs every time one of the nested `Frame`s is dealloc'd, so I can see how far it got at the point where it crashed.

No crash:
- 5645
- 5530

Crash:
- 12136 (crashed with 4476 to go (7760 complete))
- 9853 (crashed with 2193 to go (_also_ 7760 complete))
- 12342 (crashed with 4682 to go (7760 complete))

Then I got rid of the `return` statement at the end of the block above, so the rest of `drop` can run but it still prints out the count. I saw a case where a chain of 11681 was dealoc'd, and it didn't stack overflow. Ran it again with 9126 chain length, and still no crash.

2020-04-23 08:55 UTC, nicokoch commented on src/source/buffered.rs
> +                        mem::replace(self, next_data);
This will trigger a warning on nightly rust, see rust-lang/rust#71256
You can just assign instead.
`*self = next_data`

2020-08-02 23:21 UTC, stevebob commented
Squashed fix up commits and rebased onto the tip of master

2021-02-21 00:37 UTC, stevebob commented
@nicokoch any thoughts on whether this change is ok to merge? Would you like me to rebase it onto master?

2022-01-12 14:51 UTC, mathstuf commented
Bump?

2022-01-12 15:21 UTC, est31 requested changes
Ok except for detail. Sorry for the delay.

2022-01-12 15:33 UTC, est31 approved these changes
This has sat unreviewed for more than a year. I'm merging despite the small issue. Subsequent PRs for improvement are welcome!

2022-01-12 15:34 UTC, merged

2022-01-12 23:58 UTC, gridbugs commented
Thanks for the merge @est31! I'll make the change you suggested in a subsequent PR.