Fix crackling audio when using Sink
RustAudio/rodio pull request #320
Opened 2020-10-02 15:26 UTC by HalfVoxel

Fixes #318.
Fixes #319.
Fixes #266.

Combined, these two fixes also fix crackling audio on my computer. The reason for the crackling audio was that Done did not implement size_hint so it would always fall back to a frame size of 512. Somewhere down the pipeline this causing crackling every 512 samples I suspect (which might be worth fixing too).

The current_frame_length fix is necessary because in my case I was playing from a sound file and it returns a size hint on the format `(very_large_number, Some(very_large_number))` and the current_frame_length method would just ignore that and fall back to a frame length of 512 samples anyway.

This might also fix #225 (I am running on linux, so I cannot test that).

2020-10-02 19:44 UTC, est31 requested changes
There should still be an upper bound to the length. It influences buffer sizes for example. If THRESHOLD is too small and  that causes issues, one can define another larger constant by which to clamp the returned value, e.g. 4096.

2020-10-03 09:21 UTC, HalfVoxel commented
Is this method really the right place to clamp it though? If a method further down the pipeline needs to break things up into chunks for more efficient buffering it should be free to do that anyway, right?

The frame_len is only supposed to be an upper bound on the allowed buffer if I understand it correctly.

2020-10-03 09:22 UTC, HalfVoxel commented
In a test I changed it to always return Some(4096) and that does get rid of the crackling as well.

2020-10-03 09:29 UTC, est31 commented
Hmm yeah I think I misread `src/source/buffered.rs`. It's fine.

2020-10-03 09:29 UTC, est31 approved these changes
Thanks!

2020-10-03 09:30 UTC, merged

2020-10-03 09:42 UTC, HalfVoxel commented
Hmmm, actually UniformSourceIterator::bootstrap does use the frame size without any limits. Might want to have some limit there.

2020-10-03 09:45 UTC, est31 commented
@HalfVoxel PRs welcome!

2020-10-03 09:53 UTC, HalfVoxel commented
I would gladly open one, but I'm not sure what the best limit value is? I haven't got enough insight into the library to have a feel for the possible consequences.

2020-10-03 09:59 UTC, est31 commented
buffered.rs uses 32768. I guess that value is okay.

2020-10-03 15:05 UTC, Xaeroxe commented
![giphy](https://user-images.githubusercontent.com/6182002/94994857-92e97880-0557-11eb-883b-1e3cbdffc688.gif)