SampleRateConverter: Improve testsuite documentation/comments
RustAudio/rodio pull request #328
Opened 2020-10-08 02:00 UTC by nbraud

Apologies, I forgot to push this commit before you merged #324.

2020-10-08 02:02 UTC, nbraud commented
PS: Once this is merged, would you be willing to label it `hacktoberfest-accepted`, along with #324 and cpal#483 ?

2020-10-08 02:09 UTC, est31 commented
@nbraud done, enjoy your t shirt :)

2020-10-08 02:09 UTC, est31 commented on src/conversions/sample_rate.rs
> +    // Remove once cpal 0.12.2 is released and the dependency is updated
Still needs a TODO

2020-10-08 02:10 UTC, est31 commented on src/conversions/sample_rate.rs
> +        /// Checking that, after multiplying the sample rate by k, every k-th
please use Check here not Checking

2020-10-08 02:10 UTC, est31 requested changes
see inline comments

2020-10-08 11:22 UTC, nbraud commented
Feedback addressed, thanks again  <3

2020-10-09 03:23 UTC, est31 approved these changes
Thanks!

2020-10-09 03:23 UTC, merged