Better error handling for stream creation
RustAudio/rodio pull request #350
Opened 2021-02-07 19:15 UTC by jiminycrick

I am a contributor to Veloren (an open source game) and we have had players with different devices reaching the expects in stream.rs. This MR removes all the expects and replaces it with some error handling. Instead of panicking, this will allow the program to decide what to do with the error.
You can ignore the changes in src/decoder/mod.rs, that was just a result of cargo fmt.

2021-02-12 23:38 UTC, LiquidityC commented
This PR would also help me a lot. Have an application that offers audio support but it's not needed. Some users run on systems that don't have audio at all (VPS, WSL) which is fine, I have code to deal with the "no audio" situation. But theses users now get an error from inside rodio which I can't capture and deal with and then everything crashes.

2021-02-13 04:22 UTC, est31 requested changes
This is good for the most part, but could you separate the rustfmt changes from the actual behaviour changes?

Also I wonder if there are other places in the code base where expect is used where it should not be. This PR constitutes a breaking change and would require a new semver breaking release. I don't want to be in the same situation if you discover another place in a few weeks :).

2021-02-14 21:53 UTC, est31 approved these changes
Thanks! This PR looks great now. I wonder about the other places that unwrap/expect is used.  Before this PR gets merged, it'd be great to have a survey for them to check whether any situation would benefit from passing on the error instead of unwrapping.

2021-02-14 22:53 UTC, jiminycrick commented
There are no more `expect()`s in the codebase. Two unwraps that I think could be replaced with `?` in `src/source/blt.rs` and `src/source/uniform.rs`. I found at least one other place where an unwrap could be replaced with an unwrap_or but the documentation comment says that it is supposed to panic there.

2021-02-14 23:00 UTC, jiminycrick commented
I should also note that in the case of the `stream.rs` code all the functions that were panicking return Results so changing the internal error handling shouldn't have any effect on the API.

2021-02-15 00:47 UTC, est31 commented
> all the functions that were panicking return Results so changing the internal error handling shouldn't have any effect on the API.

Huh thought the CpalDeviceExt trait were public but seems no. The `StreamError` enum is public though and not marked as non exhaustive so extending it is a breaking change.

2021-03-28 20:41 UTC, Imberflur commented
What is the status on this?

2021-03-29 08:08 UTC, est31 commented
I think this PR can go in, if rebased. Then we can release 0.14.0.

2021-04-04 00:51 UTC, jiminycrick commented
> 
> 
> I think this PR can go in, if rebased. Then we can release 0.14.0.

Rebased and ready to go :D

2021-05-02 10:46 UTC, alexheretic commented
This looks good to me :+1: , I was in the area and pretty much implemented the same changes. One thing I did differently was add _thiserror_ dependency and flatten the cpal errors into a renamed `OutputStreamError`.

I'll leave it here as an idea, feel free to discard. Also, in any case, we may as well use _thiserror_ to compact the code as cpal already pulls it in.

```rust
/// Errors that can occur working with output streams.
///
/// Caused by [`cpal::PlayStreamError`], [`cpal::BuildStreamError`],
/// [`cpal::DefaultStreamConfigError`].
#[derive(Debug, thiserror::Error)]
pub enum OutputStreamError {
    /// The device associated with the stream is no longer available.
    #[error("the device associated with the stream is no longer available")]
    DeviceNotAvailable,
    /// The specified stream configuration is not supported.
    #[error("The requested stream configuration is not supported by the device.")]
    StreamConfigNotSupported,
    /// Returned if e.g. the default input format was requested on an output-only audio device.
    #[error("The requested stream type is not supported by the device.")]
    StreamTypeNotSupported,
    /// We called something the C-Layer did not understand
    ///
    /// On ALSA device functions called with a feature they do not support will yield this. E.g.
    /// Trying to use capture capabilities on an output only format yields this.
    #[error("The requested device does not support this capability (invalid argument)")]
    InvalidArgument,
    /// Occurs if adding a new Stream ID would cause an integer overflow.
    #[error("Adding a new stream ID would cause an overflow")]
    StreamIdOverflow,
    /// See the `BackendSpecificError` docs for more information about this error variant.
    #[error(transparent)]
    BackendSpecific(#[from] cpal::BackendSpecificError),
}

impl From<cpal::PlayStreamError> for OutputStreamError {
    fn from(err: cpal::PlayStreamError) -> Self {
        use cpal::PlayStreamError::*;
        match err {
            DeviceNotAvailable => Self::DeviceNotAvailable,
            BackendSpecific { err } => err.into(),
        }
    }
}

impl From<cpal::BuildStreamError> for OutputStreamError {
    fn from(err: cpal::BuildStreamError) -> Self {
        use cpal::BuildStreamError::*;
        match err {
            DeviceNotAvailable => Self::DeviceNotAvailable,
            StreamConfigNotSupported => Self::StreamConfigNotSupported,
            InvalidArgument => Self::InvalidArgument,
            StreamIdOverflow => Self::StreamIdOverflow,
            BackendSpecific { err } => err.into(),
        }
    }
}

impl From<cpal::DefaultStreamConfigError> for OutputStreamError {
    fn from(err: cpal::DefaultStreamConfigError) -> Self {
        use cpal::DefaultStreamConfigError::*;
        match err {
            DeviceNotAvailable => Self::DeviceNotAvailable,
            StreamTypeNotSupported => Self::StreamTypeNotSupported,
            BackendSpecific { err } => err.into(),
        }
    }
}
```

2021-05-02 11:33 UTC, merged

2021-05-02 11:35 UTC, est31 commented
Merged. Sorry for the delay!

Regarding your suggestion @alexheretic, personally I'd prefer to avoid adding dependencies like `thiserror`.